Repository sergeykoryagin/bank, pull requests merged in 2022-03, with the labels that each got.

#55 KEK-32 fix game page layout
  bank-client/src/components/UI/BankComponent/index.module.sass
  bank-client/src/components/UI/Input/index.module.sass
  bank-client/src/hooks/useAuth.ts
  bank-client/src/pages/Game/index.module.sass
  bank-client/src/pages/Game/index.tsx
  bank-server/src/app.gateway.ts
Labels: frontend

#56 safari browser: fix game connecting
  bank-client/src/utils/setupSocketListeners.ts
Labels: frontend

#58 add reconnect feature
  bank-client/src/components/modals/JoinGameModal/index.tsx
  bank-client/src/interfaces/game-response.ts
  bank-client/src/utils/setupSocketListeners.ts
  bank-server/src/app.gateway.ts
  bank-server/src/app.service.ts
  bank-server/src/game/game.ts
Labels: feature, frontend, backend

#59 add using enviroment variables
  bank-client/.env
  bank-client/src/context/SocketContext/index.tsx
  bank-server/.env
  bank-server/.gitignore
  bank-server/package.json
  bank-server/src/app.module.ts
  bank-server/src/main.ts
  bank-server/yarn.lock
Labels: frontend, backend

#62 add ci/cd
  .dockerignore
  .github/workflows/node.js.yml
  Dockerfile
  bank-client/.env
Labels: DevOps

#66 Kek 76 Добавлена возможность подключения через доменное имя
  bank-client/.env
  bank-server/src/app.gateway.ts
Labels: DevOps
